window.LIPECARE_APP_VERSION = window.LIPECARE_APP_VERSION || "0.1.17";
window.LIPECARE_DEPLOY_NUMBER = window.LIPECARE_DEPLOY_NUMBER || "21";
window.LIPECARE_DEPLOY_VERSION = window.LIPECARE_DEPLOY_VERSION || "local";
window.LIPECARE_COMMIT_SHA = window.LIPECARE_COMMIT_SHA || "sem-commit";
